sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_84ca2c94b925_key -iv $encrypted_84ca2c94b925_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1

#install SFDX CLI
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx plugins:install salesforcedx@pre-release

- sfdx --version
- sfdx plugins --core

#headlessly auth into production org
- sfdx force:auth:jwt:grant --clientid 3MVG9SemV5D80oBc6e6VuMv1rns1SCNFk2iOTL7Vxjc5QRRy6qwQqh79yUrT8pYhJHleHNJ2eyvf9Jm1vrPb. --jwtkeyfile assets/server.key
  --username jqian-tdx2019@force.com --setdefaultusername -a ProdOrg

script:

# create a new dev sandbox for integration testing
#- sfdx force:org:create -t sandbox -u ProdOrg SandboxName=jqTdx1 LicenseType=DEVELOPER -a cisbxorg -w 60 

# OR clone a preconfiged dev sandbox for testing
#- sfdx force:org:clone -t sandbox -u ProdOrg SandboxName=ciclone SourceSandboxName=preConfg -a cisbxorg -w 60

# monitor sandbox progression
- sfdx force:org:status -n jqTdx1 -u ProdOrg

# deploy metadata source
- sfdx force:source:deploy -u cisbxorg -p force-app -w 30

# OR install the package to the sandbox for package development
# - sfdx force:package:install 

# run extensive integration apex test
- sfdx force:apex:test:run -u cisbxorg --wait 10

